apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-service-a
  name: nodejs-service-a
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodejs-service-a
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-service-a
    spec:
      containers:
        - image: localhost:5000/tiagoboeing/nodejs-service-a
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: nodejs-service-a
          name: nodejs-service-a
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
