apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-service-a
  name: nodejs-service-a
  namespace: workshop-dev
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30367
      port: 3000 # converte o tráfego da 3000 do pod para nodePort do node (do cluster)
      protocol: TCP
      targetPort: 3000 # porta do pod
  selector:
    app: nodejs-service-a # nome do deployment em metadata.labels.app
  sessionAffinity: None
  type: NodePort
