apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    version: v1
    app: mongodb

spec:
  selector:
    app: mongodb
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
