apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
    version: v1

spec:
  containers:
    - name: mongodb
      image: "mongo:4.4.11"

      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi

      ports:
        - containerPort: 27017
