apiVersion: v1
kind: Pod
metadata:
  name: nodejs-express-pod
  labels:
    version: v1
    app: nodejs-express

spec:
  containers:
    - name: nodejs-express
      image: tiagoboeing.azurecr.io/nodejs-express:latest
      ports:
        - containerPort: 3000
      env:
        - name: MONGO_URL
          value: 10.244.1.8
        - name: MESSAGE
          value: Running on AKS

  imagePullSecrets:
    - name: acr-credentials
