apiVersion: v1
kind: Pod

metadata:
  name: nodejs-express-pod
  labels:
    version: v1
    app: nodejs-express

spec:
  containers:
    - name: nodejs-express
      image: tiagoboeing/nodejs-express:latest

      ports:
        - containerPort: 3000

      env:
        - name: MONGO_URL
          value: mongodb-svc

        - name: MESSAGE
          value: Running with Pod spec
